version: 2
updates:
  - package-ecosystem: pip
    directory: "/src"
    schedule:
      interval: "daily"
    # open-pull-requests-limit: 10

  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
